ALTER TABLE users
ADD COLUMN IF NOT EXISTS credit_limit DECIMAL(10, 2) DEFAULT 0;
ALTER TABLE users
ADD COLUMN IF NOT EXISTS current_debt DECIMAL(10, 2) DEFAULT 0;
ALTER TABLE sales
ADD COLUMN IF NOT EXISTS payment_status VARCHAR(20) DEFAULT 'PAID';
-- 'PAID', 'PENDING'